global:
  scrape_interval:     10s
  evaluation_interval: 10m

scrape_configs:
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['localhost:9090']
  - job_name: 'application'
    static_configs:
      - targets: ['dApp:8080']
