version: "3.3"
services:

  dApp:
    build: .
    image: trltest
    ports:
      - 80:8080

  dProm:
    image: prom/prometheus:v2.1.0
    ports:
      - 9090:9090
    volumes:
      - ./prom/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - 'dApp'
      
  dGraf:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./graf/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./graf/gf.env
    depends_on:
      - 'dProm'